### ISSUE TITLE
06_VLF_Fix.sql file looks to be the same as 05_VLF_AutoFix.sql

### ISSUE THREAD

**Issue by jvogler01** [tboggiano/autofix-vlfs#1]
Hi Tracy - it looks like files 05 and 06 are the same?  I had to go back [here](http://tracyboggiano.com/archive/2017/09/high-vlf-count-fix/) to get the correct file for 06_VLF_Fix.sql.  Thanks!

**Comment by tboggiano** [comment]
Uploaded correct file.

**Comment by jvogler01** [comment]
You are awesome!  And a sincere thank you for all of your contributions to the SQL community, Tracy!  
Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: Tracy Boggiano <notifications@github.com> Date: 11/15/17  5:23 PM  (GMT-08:00) To: tboggiano/autofix-vlfs <autofix-vlfs@noreply.github.com> Cc: jvogler01 <fritzdog96@gmail.com>, Author <author@noreply.github.com> Subject: Re: [tboggiano/autofix-vlfs] 06_VLF_Fix.sql file looks to be the same
  as 05_VLF_AutoFix.sql (#1) 
Uploaded correct file.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tboggiano/autofix-vlfs","title":"tboggiano/autofix-vlfs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tboggiano/autofix-vlfs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tboggiano in #1: Uploaded correct file."}],"action":{"name":"View Issue","url":"https://github.com/tboggiano/autofix-vlfs/issues/1#issuecomment-344784822"}}}
